name: bachelor_thesis_project

channels:
  - conda-forge
  - huggingface

dependencies:
  - pip
  - python=3.8.13
  - setuptools
  - wheel
  - spacy
  - datasets
  - ipywidgets

  - pip:
    - argilla[server]
    - spacy[transformers,lookups]
    - matplotlib
    - jsonlines
    - flake8
