name: bachelor_thesis_project

channels:
  - conda-forge
  - huggingface

dependencies:
  - pip==22.2.2
  - python==3.8.13
  - setuptools==65.5.0
  - wheel==0.37.1
  - spacy==3.4.2
  - spacy-transformers==1.1.8
  - datasets==2.6.1
  - ipywidgets==8.0.2

  - pip:
    - argilla[server]==1.0.1
    - spacy-lookups-data==1.0.3
    - matplotlib==3.6.2
    - jsonlines==3.1.0
    - flake8
